digital-asset/daml-js

- CHANGELOG.md
- CONTRIBUTING.md
- LICENSE.txt
- README.DOCS.md
- README.md
- package-lock.json
- package.json
- tsconfig-docs.json
Changelog, license, contributing guidelines, readme and a few changes to
the package manifest to follow a documented release process.
> Add all files necessary before the release

- grpc-codegen.sh
- src/codec/CommandCodec.ts
- src/codec/CreateAndExerciseCommandCodec.ts
- src/index.ts
- src/model/Command.ts
- src/model/CreateAndExerciseCommand.ts
- src/validation/CommandValidation.ts
- src/validation/CreateAndExerciseCommandValidation.ts
- test/arbitrary/ArbitraryCommand.ts
- test/arbitrary/ArbitraryCreateAndExerciseCommand.ts
- test/client/CommandClient.spec.ts
- test/client/CommandSubmissionClient.spec.ts
- test/codec/Codec.spec.ts
- test/validation/AllObjects.spec.ts
> Add support for CreateAndExercise

- CHANGELOG.md
- grpc-codegen.sh
- src/client/CommandClient.ts
- src/codec/CompletionCodec.ts
- src/codec/SubmitAndWaitForTransactionIdResponseCodec.ts
- src/codec/SubmitAndWaitForTransactionResponseCodec.ts
- src/codec/SubmitAndWaitForTransactionTreeResponseCodec.ts
- src/index.ts
- src/model/SubmitAndWaitForTransactionIdResponse.ts
- src/model/SubmitAndWaitForTransactionResponse.ts
- src/model/SubmitAndWaitForTransactionTreeResponse.ts
- src/validation/CompletionValidation.ts
- src/validation/SubmitAndWaitForTransactionIdResponseValidation.ts
- src/validation/SubmitAndWaitForTransactionResponseValidation.ts
- src/validation/SubmitAndWaitForTransactionTreeResponseValidation.ts
- test/arbitrary/ArbitraryCompletion.ts
- test/arbitrary/ArbitrarySubmitAndWaitForTransactionIdResponse.ts
- test/arbitrary/ArbitrarySubmitAndWaitForTransactionResponse.ts
- test/arbitrary/ArbitrarySubmitAndWaitForTransactionTreeResponse.ts
- test/client/CommandClient.spec.ts
- test/client/DummyCommandServiceClient.ts
- test/client/DummyServer.ts
- test/codec/Codec.spec.ts
- test/validation/AllObjects.spec.ts
Fixes #19
Also improves on existing in `CHANGELOG.md` (only the `UNRELEASED` section) to add issue links.
> Add support for submit and wait for result

- CHANGELOG.md
- grpc-codegen.sh
- src/codec/ExercisedEventCodec.ts
- src/model/ExercisedEvent.ts
- src/validation/ExercisedEventValidation.ts
- test/arbitrary/ArbitraryEvent.ts
- test/codec/Codec.spec.ts
> Include exercise result in exercised events

- .gitignore
- azure-pipelines.yml
- grpc-codegen.sh
- package.json
- reserve-port.js
- sandbox-start.sh
- test/integration/LedgerIdentityClient.spec.ts
- test/integration/src/daml.yaml
- test/integration/src/daml/IntegrationTests.daml
Fixes #36
This is the first test to establish the testing framework: a script in
ran before the tests to ensure that the SDK 0.12.16 is installed and run
a sandbox with testing packages.
The LedgerIdentityClient is tested as a proof of concept before applying
this approach to other clients.
gRPC reflection service is also introduced for future use (feature
discovery to target multiple versions of the ledger).
> Add integration tests

- CHANGELOG.md
- src/codec/CommandCodec.ts
- src/codec/EventCodec.ts
- src/codec/LedgerOffsetCodec.ts
- src/codec/TreeEventCodec.ts
- src/codec/ValueCodec.ts
- src/util/ErrorMessages.ts
> Improve deserialization error message

- CHANGELOG.md
- src/codec/CreatedEventCodec.ts
- src/model/CreatedEvent.ts
- src/validation/CreatedEventValidation.ts
- test/arbitrary/ArbitraryEvent.ts
> Add agreement text to created events

- CHANGELOG.md
- README.md
- src/helpers/ValueHelpers.ts
- src/index.ts
- test/helpers/ValueHelpers.spec.ts
- test/validation/Tree.spec.ts
> Add value helpers

- CHANGELOG.md
- src/reporting/HumanReadableReporter.ts
- src/validation/IntegerString.ts
- src/validation/Validation.ts
- src/validation/ValueValidation.ts
- test/arbitrary/ArbitraryIntegerString.ts
- test/arbitrary/ArbitraryRecordValueVariant.ts
- test/validation/IntegerString.spec.ts
- test/validation/Native.spec.ts
- test/validation/index.ts
> Catch invalid string representation of integer values

- src/model/Checkpoint.ts
- src/model/Command.ts
- src/model/Event.ts
- src/model/GetLedgerConfigurationResponse.ts
- src/model/GetTransactionTreesResponse.ts
- src/model/GetTransactionsResponse.ts
- src/model/LedgerOffset.ts
- src/model/Value.ts
Completes the work done in #61 to fix #58
> Fill in the gaps left in docs

- azure-pipelines.yml
Restores the work done on #48.
Fixes #65.
> Run Blackduck scan

- CHANGELOG.md
- src/validation/ValueValidation.ts
- test/arbitrary/ArbitraryRecordValueVariant.ts
> Validation of optional DAML values requires 'optional' type tag

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- package-lock.json
- package.json
* update changelog
* fix outstanding typos
* bump version
> Prepare 0.6.1 release

- azure-pipelines.yml
> Make Azure Pipelines download a specific SDK version

- grpc-codegen.sh
- package-lock.json
- package.json
This is to incorporate script to pull admin protobuf.
> Upgrade SDK version to 0.12.25

- CHANGELOG.md
- src/codec/CreatedEventCodec.ts
- src/helpers/ValueHelpers.ts
- src/model/CreatedEvent.ts
- src/validation/CreatedEventValidation.ts
- test/arbitrary/ArbitraryEvent.ts
- test/codec/Codec.spec.ts
- test/integration/IntegrationTests.spec.ts
> Add signatories and observers to created events

- CHANGELOG.md
- src/codec/ValueCodec.ts
- src/helpers/ValueHelpers.ts
- src/model/Value.ts
- src/validation/ValueValidation.ts
- test/arbitrary/ArbitraryRecordValueVariant.ts
- test/integration/IntegrationTests.spec.ts
- test/integration/src/daml/IntegrationTests.daml
> Support enum values

- src/client/NodeJsTransactionClient.ts
- test/client/TransactionClient.spec.ts
- test/integration/IntegrationTests.spec.ts
> Make getTransactionTrees set verbose to true by default

- CHANGELOG.md
- src/client/DamlLedgerClient.ts
- src/client/LedgerClient.ts
- test/integration/IntegrationTests.spec.ts
> Give a way to pass options to be forwarded to the underlying gRPC client

- CHANGELOG.md
- azure-pipelines.yml
- grpc-codegen.sh
- sandbox-start.sh
- src/codec/CommandsCodec.ts
- src/codec/LedgerConfigurationCodec.ts
- src/codec/PackageDetailsCodec.ts
- src/model/Commands.ts
- src/model/LedgerConfiguration.ts
- src/model/PackageDetails.ts
- src/validation/CommandsValidation.ts
- src/validation/LedgerConfigurationValidation.ts
- test/arbitrary/ArbitraryCommands.ts
- test/arbitrary/ArbitraryLedgerConfiguration.ts
- test/client/CommandClient.spec.ts
- test/client/CommandSubmissionClient.spec.ts
- test/client/LedgerClient.spec.ts
- test/codec/Codec.spec.ts
- test/codec/CodecReference.ts
- test/integration/IntegrationTests.spec.ts
- test/integration/src/daml.yaml
- test/integration/src/uploadDar/daml.yaml
> Support the latest available snapshot available via Maven

- package-lock.json
- package.json
This should also upgrade a number of transitive dependencies, fixing the currently outstanding security vulnerabilities.
> Upgrade grpc-js and grpc_tools_node_protoc_ts
